# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-14 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(blank=True, default='profile_photo/sea_side.jpeg', upload_to='profile_photo/'),
        ),
    ]
