# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-15 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20191014_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
